### ISSUE TITLE
Issue with option -f

### ISSUE THREAD

**Issue by sukuanliu** [EvanForsythe/Squeakuences#56]
python3 squeakuences -i CDS_INPUTcopy -o squeakuences_OUTPUT_c -l -f

Log provided below. Thank you.

================================
Commencing Squeakuences Cleanup
================================
You've activated the -f flag.
The file name will be inserted at the beginning of all sequences cleaned.
You've activated the -l flag.
A log file with information about each fasta file processed will be written in the output directory.
--------------------------------
Squeakuences will clean sequence ids will the following settings:

Chop method (-c): words
Maximum sequence id character length (-m): 70
Prepend file name (-f): True
Underscores (-u): False
Ignore characters (-x): None
--------------------------------
You've input a directory.
The following file(s) will be cleaned: ['Solanum_lycopersicum.fa']
--------------------------------
The provided output path does not lead to an existing directory.
A directory was created at: /Users/Sukuan/Library/CloudStorage/OneDrive-Colostate/CP-ERC/WORK/002Squeakuences/squeakuences_OUTPUT_c
Squeakuences files will be written in this new directory.
--------------------------------
An existing log file was not detected.
A new log file was created at: /Users/Sukuan/Library/CloudStorage/OneDrive-Colostate/CP-ERC/WORK/002Squeakuences/squeakuences_OUTPUT_c/log.tsv
--------------------------------
Now processing Solanum_lycopersicum.fa
...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/Sukuan/Library/CloudStorage/OneDrive-Colostate/CP-ERC/WORK/002Squeakuences/squeakuences/__main__.py", line 51, in <module>
    squeaky_file.generate(file, argsDict)
  File "/Users/Sukuan/Library/CloudStorage/OneDrive-Colostate/CP-ERC/WORK/002Squeakuences/squeakuences/squeaky_file.py", line 33, in generate
    cleanSequenceId = squeakify.squeakify(sequenceID, argsDict)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Sukuan/Library/CloudStorage/OneDrive-Colostate/CP-ERC/WORK/002Squeakuences/squeakuences/squeakify.py", line 11, in squeakify
    endID = attachFileName(endID, argsFlags['addFileName'])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Sukuan/Library/CloudStorage/OneDrive-Colostate/CP-ERC/WORK/002Squeakuences/squeakuences/squeakify.py", line 58, in attachFileName
    attachFileName = camelCase(attachFileName)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Sukuan/Library/CloudStorage/OneDrive-Colostate/CP-ERC/WORK/002Squeakuences/squeakuences/squeakify.py", line 27, in camelCase
    wordList = re.split(r'([^a-zA-Z0-9])', sequenceID)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniforge/base/lib/python3.12/re/__init__.py", line 207, in split
    return _compile(pattern, flags).split(string, maxsplit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'bool'

**Comment by EvanForsythe** [comment]
This issue is fixed was fixed in most recent branch merge. Closing issue.
